nota1 = input("Digite a primeira nota:")
nota2 = input("Digite a segunda nota:")
nota3 = input("Digite a terceira nota:")
nota4 = input("Digite a quarta nota:")
tempnota1 = (float(nota1))
tempnota2 = (float(nota2))
tempnota3 = (float(nota3))
tempnota4 = (float(nota4))
media = ((tempnota1 + tempnota2 + tempnota3 + tempnota4) /4)

print("A média aritmética é", media)